PubMatic-OpenWrap/Prebid.js

- adapters.json
- src/adapters/kargo.js
```
{
params: {
// ...
}
}
```
> added kargo adapter

- modules.json
- modules/pubmaticServerBidAdapter.js
- modules/pubmaticServerBidAdapter.md
- src/utils.js
- test/spec/modules/pubmaticServerBidAdapter_spec.js
```
{
params: {
// ...
}
}
```
> S2 s code review changes

- modules/appnexusBidAdapter.js
```
{
params: {
// ...
}
}
```
> added districtm as alias for appnexus

- modules.json
- modules/adgBidAdapter.js
```
{
params: {
// ...
}
}
```
> Add Ad Generation Bid Adapter

- modules/pubmaticBidAdapter.js
- test/spec/modules/pubmaticBidAdapter_spec.js
```
{
params: {
// ...
}
}
```
> Update the gdpr to strict numbers

- modules/pubmaticBidAdapter.js
- test/spec/modules/pubmaticBidAdapter_spec.js
```
{
params: {
// ...
}
}
```
> 1.9.0 pm fix

- modules/consentManagement.js
- test/spec/modules/consentManagement_spec.js
```
{
params: {
// ...
}
}
```
> Update the ConsentMgmt module to use getConsentData method

- modules/pubmaticBidAdapter.js
```
{
params: {
// ...
}
}
```
> Prebid 1.x upgrade gdpr 1.13

- modules/audienceNetworkBidAdapter.js
- test/spec/modules/audienceNetworkBidAdapter_spec.js
```
{
params: {
// ...
}
}
```
> UOE-3651 Changed Platform id in adapter

- modules/pubmaticServerBidAdapter.js
- test/spec/modules/pubmaticServerBidAdapter_spec.js
```
{
params: {
// ...
}
}
```
> Psl changes uoe 3930

- modules/pubmaticBidAdapter.js
- src/ajax.js
- test/spec/modules/pubmaticBidAdapter_spec.js
```
{
params: {
// ...
}
}
```
> Prebid 1.x upgrage gdpr 1.21

- modules/pubmaticBidAdapter.js
- modules/pubmaticServerBidAdapter.js
- test/spec/modules/pubmaticServerBidAdapter_spec.js
```
{
params: {
// ...
}
}
```
> Server adapter multisize support

- modules/rdnBidAdapter.js
- modules/rdnBidAdapter.md
- modules/teadsBidAdapter.js
- modules/teadsBidAdapter.md
- test/spec/modules/rdnBidAdapter_spec.js
- test/spec/modules/teadsBidAdapter_spec.js
```
{
params: {
// ...
}
}
```
> Prebid121 rdnadapter

- modules/rdnBidAdapter.js
- modules/rdnBidAdapter.md
- modules/teadsBidAdapter.js
- modules/teadsBidAdapter.md
- test/spec/modules/rdnBidAdapter_spec.js
- test/spec/modules/teadsBidAdapter_spec.js
```
{
params: {
// ...
}
}
```
> Teadsandrakutenadapters

- package.json
```
{
params: {
// ...
}
}
```
> changed default name-space from "pbjs" to "owpbjs"

- modules/pubmaticServerBidAdapter.js
- test/spec/modules/pubmaticServerBidAdapter_spec.js
```
{
params: {
// ...
}
}
```
> Uoe 3967 log mi value

- modules/yieldoneBidAdapter.js
- modules/yieldoneBidAdapter.md
- test/spec/modules/yieldoneBidAdapter_spec.js
```
{
params: {
// ...
}
}
```
> merged yieldone adapter from prebid master into nightly for openwrap

- modules/pubmaticServerBidAdapter.js
- test/spec/modules/pubmaticServerBidAdapter_spec.js
```
{
params: {
// ...
}
}
```
> Rubicon issue

- modules.json
- modules/.submodules.json
- modules/customIdSystem.js
- modules/id5IdSystem.js
- modules/pubmaticBidAdapter.js
- modules/pubmaticServerBidAdapter.js
- modules/unifiedIdSystem.js
- modules/userId/index.js
- test/spec/modules/appierAnalyticsAdapter_spec.js
- test/spec/modules/userId_spec.js
- test/spec/unit/core/targeting_spec.js
Reverts PubMatic-OpenWrap/Prebid.js#354
> Revert "Revert "Open identity""

- modules/customIdSystem.js
- modules/pubmaticBidAdapter.js
Renamed Custom ID to firstpartyid
> First Party Id name updated for cookies

- modules/pubmaticBidAdapter.js
- modules/pubmaticServerBidAdapter.js
> Pubmaticalias

- modules/pubCommonIdSystem.js
- modules/pubmaticServerBidAdapter.js
- modules/userId/index.js
- test/spec/modules/userId_spec.js
#CriteoID Changes
#PubCommonId System Changes
#Sending Eids to Pubmatic serve
> IdentityHubChanges

- modules.json
- modules/dfpAdServerVideo.js
- src/videoCache.js
- test/spec/modules/pubmaticServerBidAdapter_spec.js
OpenWrap Release for Supporting Client Side Video
> OpenWrap Support for Client Side Video

- modules/pubmaticBidAdapter.js
Consuming bid.id for logging it in tracker and logger
> adding sspId

- modules/adgenerationBidAdapter.js
UOE-6262 : OpenWrap: Add Secondary Ad Generation Bidder
Story
> UOE-5262 : OpenWrap: Add Secondary Ad Generation Bidder

- modules/pubmaticBidAdapter.js
- modules/pubmaticBidAdapter.md
- test/spec/modules/pubmaticBidAdapter_spec.js
Using BlueBillyWig renderer in Pubmatic Adapter.
> Bluebillywig outstream renderer

- modules/pubmaticAnalyticsAdapter.js
- test/spec/modules/pubmaticAnalyticsAdapter_spec.js
> Staged Nightly update with regex fix

- modules/pubmaticBidAdapter.js
- test/spec/modules/pubmaticBidAdapter_spec.js
Changed netRevenue value from false to true
> Changed netRevenue from false to true

- modules/pubmaticAnalyticsAdapter.js
[5231] Added a function which takes bidId as input and fires BidWon handler for the Bid
> [5231] Native Creative rendering in friendly iframe using OW creative template while using prebid analytics

- modules/pubmaticAnalyticsAdapter.js
- src/constants.json
[UOE-5231] Updated Native Keys and added event listener for Native tracker
> [5231]Native Creative rendering in friendly iframe using OW creative template while using prebid analytics

- modules/pubmaticBidAdapter.js
- test/spec/modules/pubmaticBidAdapter_spec.js
Adding support in PubMatic bid adapter for First-Party Data
> PubMatic bid adapter: support for FPD

- modules/prebidJSDebugUI.js
- src/adloader.js
> Added DebugUI module

- modules/pubmaticAnalyticsAdapter.js
- src/constants.json
Added support for Native format
> support for Native in PrebidSame

- modules/pubmaticBidAdapter.js
> Removed dfp ad slot code

- modules/pubmaticBidAdapter.js
- modules/pubmaticServerBidAdapter.js
Added dfp adslot code in CS and Server side bid adapter
> Added dfp adslot code

- modules/pubmaticAnalyticsAdapter.js
- test/spec/modules/pubmaticAnalyticsAdapter_spec.js
Support for Bidder Aliases, where bidder code will be logged in logger and tracker call
> Added bidder code in logger and tracker bid alias

- modules/pubmaticBidAdapter.js
> Support for native without having size defined for native asset

- modules/pubmaticAnalyticsAdapter.js
Removed code converting bidder to lowercase, which was causing error on reporting side.
```
{
params: {
// ...
}
}
```
> Removed code converting bidder to lowercase

- modules/userId/index.js
```
{
params: {
// ...
}
}
```
> changes to initialise a module configured from the page for OW profile

- modules/quantcastIdSystem.js
- modules/quantcastIdSystem.md
- modules/userId/userId.md
- test/spec/modules/quantcastIdSystem_spec.js
```
{
params: {
// ...
}
}
```
> changes from latest version of quantcast ID module

- modules/userId/index.js
```
{
params: {
// ...
}
}
```
> added function to store user identity object

- modules/priceFloors.js
- modules/pubmaticAnalyticsAdapter.js
- test/spec/modules/pubmaticAnalyticsAdapter_spec.js
Added support for logging Floor Module related parameters in logger
> Added support for logging Floor Module related parameters in logger

- modules/pubmaticAnalyticsAdapter.js
- test/spec/modules/pubmaticAnalyticsAdapter_spec.js
Added support for logging floor parameters
> Added support for logging floor parameter

- modules/pubmaticBidAdapter.js
- test/spec/modules/pubmaticBidAdapter_spec.js
```
{
params: {
// ...
}
}
```
> Added log message when Video.Placement property is not available

- modules/pubmaticAutoRefresh.js
- modules/pubmaticAutoRefresh.md
```
{
params: {
// ...
}
}
```
> Auto Refresh

- modules/pubmaticAutoRefresh.js
- modules/pubmaticAutoRefresh.md
```
{
params: {
// ...
}
}
```
> Pm auto refresh 5.x

- modules/pubmaticAutoRefresh.js
- modules/pubmaticAutoRefresh.md
- modules/userId/index.js
- test/spec/modules/userId_spec.js
```
{
params: {
// ...
}
}
```
> Merge Nightly4.x to nightly

- package.json
```
{
params: {
// ...
}
}
```
> Changed the version of fakerjs

- package.json
```
{
params: {
// ...
}
}
```
> Changed the version of faker in package json

- gulpfile.js
```
{
params: {
// ...
}
}
```
> Updated gulpfile for 5.x

- modules/pubmaticAnalyticsAdapter.js
- test/spec/modules/pubmaticAnalyticsAdapter_spec.js
Access OpenWrap's bidder aliases in case of Pb Same functionality
> Access openwraps bidder aliases in case of pb same

- modules/userId/index.js
- src/constants.json
- src/utils.js
- test/spec/modules/userId_spec.js
```
{
params: {
// ...
}
}
```
> Refreshuserid 5.20.x

- test/spec/modules/userId_spec.js
```
{
params: {
// ...
}
}
```
> Commenting publink test cases as video cache test case is failing

- modules/userId/index.js
```
{
params: {
// ...
}
}
```
> IDNT-110: Added window.gtag check

- modules/userId/eids.js
```
{
params: {
// ...
}
}
```
> ZeoTap fix: Datatype of data checked

- modules/prebidServerBidAdapter/index.js
- modules/pubmaticAnalyticsAdapter.js
- test/spec/modules/prebidServerBidAdapter_spec.js
- test/spec/modules/pubmaticAnalyticsAdapter_spec.js
```
{
params: {
// ...
}
}
```
> Added bid id and original bid id to logger and tracker call

- modules/prebidServerBidAdapter/index.js
- modules/pubmaticAnalyticsAdapter.js
- test/spec/modules/prebidServerBidAdapter_spec.js
- test/spec/modules/pubmaticAnalyticsAdapter_spec.js
```
{
params: {
// ...
}
}
```
> Using prebid generated unique bid.id in Client side

- modules/prebidServerBidAdapter/index.js
- modules/pubmaticBidAdapter.js
- modules/pubmaticServerBidAdapter.js
- test/spec/modules/pubmaticBidAdapter_spec.js
```
{
params: {
// ...
}
}
```
> Modified device.language to ISO-639 format 2 characters language

- package.json
```
{
params: {
// ...
}
}
```
> Prebid upgrade 6 27 0 20220601154841 test

- modules/prebidServerBidAdapter/index.js
- modules/pubmaticBidAdapter.js
- modules/userId/eids.js
- modules/userId/index.js
- test/spec/modules/pubmaticBidAdapter_spec.js
```
{
params: {
// ...
}
}
```
> Stop overwriting site.page, site.domain & site.ref information 

- gulpfile.js
- modules/userId/index.js
- package.json
- plugins/pbjsGlobals.js
- webpack.conf.js
```
{
params: {
// ...
}
}
```
> preliminary changes for creating separate namespace for ih only profile

- modules/pubmaticAnalyticsAdapter.js
- modules/pubmaticBidAdapter.js
- test/spec/modules/pubmaticBidAdapter_spec.js
```
{
params: {
// ...
}
}
```
> Nightly new bug fixes

- modules/module_meta.json
```
{
params: {
// ...
}
}
```
> Prebid modules

- modules/userId/index.js
```
{
params: {
// ...
}
}
```
> IDNT-320: Added support for user agent in PD string ID5 param

- gulpHelpers.js
- gulpfile.js
- src/adapterManager.js
- src/prebidIdhub.js
- webpack.conf.js
- webpack.idhub.conf.js
```
{
params: {
// ...
}
}
```
> PrebidJS: Feature/IDNT-355 Code Size Reduction

- modules/pubmaticBidAdapter.js
added reqMethod in bidderRequest to identify POST or GET call
```
{
params: {
// ...
}
}
```
> added reqMethod in bidderRequest to identify POST or GET call

- modules/pubmaticAnalyticsAdapter.js
- test/spec/modules/pubmaticAnalyticsAdapter_spec.js
\
RE2529 : Added support for browser and platform for floors
> RE2529 : Added support for browser and platform for floors

- modules/pubmaticIHAnalyticsAdapter.js
- modules/userId/index.js
- src/constants.json
- test/spec/modules/pubmaticIHAnalyticsAdapter_spec.js
```
{
params: {
// ...
}
}
```
> Ih reporting 7x

- modules/33acrossIdSystem.js
- test/spec/modules/33acrossIdSystem_spec.js
```
{
params: {
// ...
}
}
```
> backport lexicon latest changes to 7.25 based nightly branch

- gulpfile.js
```
{
params: {
// ...
}
}
```
> Nightly node14

- gulpfile.js
- modules/33acrossIdSystem.js
- test/spec/modules/33acrossIdSystem_spec.js
Sync branch with nightly_6_29_3
```
{
params: {
// ...
}
}
```
> Nightly 6 29 3

- modules/pubmaticAutoRefresh.js
```
{
params: {
// ...
}
}
```
> UOE-8520 : Checking for valid slot before initiating refresh

- src/constants.json
- test/spec/modules/userId_spec.js
```
{
params: {
// ...
}
}
```
> merge connect id changes with latest nightly

- modules/pubmaticAnalyticsAdapter.js
- modules/pubmaticBidAdapter.js
Replaced pubmatic2 as alias instead of groupm
> Replaced pubmatic2 as alias instead of groupm
